image: gcc

stages:
  - build

build:
  stage: build
  except:
   - schedules
  script: 
   - make test && make libradamsa-test

build:on-schedule:
   stage: build
   only: 
    - schedules
   script: 
    - make future

